python3 login.py fulcrum_lifting ../mocks/connect/fulcrum_lifting-logo.png ../mocks/connect/fulcrum_lifting.png ../gifs/contact/fulcrum_lifting.gif
python3 login.py 2nd_amendment_wholesale ../mocks/connect/2nd_amendment_wholesale-logo.png ../mocks/connect/2nd_amendment_wholesale.png ../gifs/contact/2nd_amendment_wholesale.gif
python3 login.py brooklyn_bedding ../mocks/connect/brooklyn_bedding-logo.png ../mocks/connect/brooklyn_bedding.png ../gifs/contact/brooklyn_bedding.gif
python3 login.py door_county_coffee ../mocks/connect/door_county_coffee-logo.png ../mocks/connect/door_county_coffee.png ../gifs/contact/door_county_coffee.gif
python3 login.py unique ../mocks/connect/unique-logo.png ../mocks/connect/unique.png ../gifs/contact/unique.gif
python3 login.py ceramo ../mocks/connect/ceramo-logo.png ../mocks/connect/ceramo.png ../gifs/contact/ceramo.gif
python3 login.py greatbaybud ../mocks/connect/greatbaybud-logo.png ../mocks/connect/greatbaybud.png ../gifs/contact/greatbaybud.gif
python3 login.py prime_roots ../mocks/connect/prime_roots-logo.png ../mocks/connect/prime_roots.png ../gifs/contact/prime_roots.gif
python3 login.py pmf ../mocks/connect/pmf-logo.png ../mocks/connect/pmf.png ../gifs/contact/pmf.gif
python3 login.py fairlife ../mocks/connect/fairlife-logo.png ../mocks/connect/fairlife.png ../gifs/contact/fairlife.gif
python3 login.py rubix ../mocks/connect/rubix-logo.png ../mocks/connect/rubix.png ../gifs/contact/rubix.gif
python3 login.py burt ../mocks/connect/burt-logo.png ../mocks/connect/burt.png ../gifs/contact/burt.gif
python3 login.py caseys ../mocks/connect/caseys-logo.png ../mocks/connect/caseys.png ../gifs/contact/caseys.gif
python3 login.py tactacam ../mocks/connect/tactacam-logo.png ../mocks/connect/tactacam.png ../gifs/contact/tactacam.gif
python3 login.py tygris ../mocks/connect/tygris-logo.png ../mocks/connect/tygris.png ../gifs/contact/tygris.gif
python3 login.py ninkasi ../mocks/connect/ninkasi-logo.png ../mocks/connect/ninkasi.png ../gifs/contact/ninkasi.gif
python3 login.py underdog_games ../mocks/connect/underdog_games-logo.png ../mocks/connect/underdog_games.png ../gifs/contact/underdog_games.gif
python3 login.py g54 ../mocks/connect/g54-logo.png ../mocks/connect/g54.png ../gifs/contact/g54.gif
python3 login.py harbor_wholesale ../mocks/connect/harbor_wholesale-logo.png ../mocks/connect/harbor_wholesale.png ../gifs/contact/harbor_wholesale.gif
python3 login.py fair_market ../mocks/connect/fair_market-logo.png ../mocks/connect/fair_market.png ../gifs/contact/fair_market.gif
python3 login.py real_avid ../mocks/connect/real_avid-logo.png ../mocks/connect/real_avid.png ../gifs/contact/real_avid.gif
python3 login.py paris_brothers ../mocks/connect/paris_brothers-logo.png ../mocks/connect/paris_brothers.png ../gifs/contact/paris_brothers.gif
python3 login.py theo_chocolate ../mocks/connect/theo_chocolate-logo.png ../mocks/connect/theo_chocolate.png ../gifs/contact/theo_chocolate.gif
python3 login.py wynk ../mocks/connect/wynk-logo.png ../mocks/connect/wynk.png ../gifs/contact/wynk.gif
python3 login.py numilk ../mocks/connect/numilk-logo.png ../mocks/connect/numilk.png ../gifs/contact/numilk.gif
python3 login.py endless_west ../mocks/connect/endless_west-logo.png ../mocks/connect/endless_west.png ../gifs/contact/endless_west.gif
python3 login.py chesterman ../mocks/connect/chesterman-logo.png ../mocks/connect/chesterman.png ../gifs/contact/chesterman.gif
python3 login.py septiscope ../mocks/connect/septiscope-logo.png ../mocks/connect/septiscope.png ../gifs/contact/septiscope.gif
python3 login.py colorado_standby ../mocks/connect/colorado_standby-logo.png ../mocks/connect/colorado_standby.png ../gifs/contact/colorado_standby.gif
python3 login.py cheribundi ../mocks/connect/cheribundi-logo.png ../mocks/connect/cheribundi.png ../gifs/contact/cheribundi.gif
python3 login.py airefco ../mocks/connect/airefco-logo.png ../mocks/connect/airefco.png ../gifs/contact/airefco.gif
python3 login.py backyard_nature_products ../mocks/connect/backyard_nature_products-logo.png ../mocks/connect/backyard_nature_products.png ../gifs/contact/backyard_nature_products.gif
python3 login.py schacht ../mocks/connect/schacht-logo.png ../mocks/connect/schacht.png ../gifs/contact/schacht.gif
python3 login.py hector ../mocks/connect/hector-logo.png ../mocks/connect/hector.png ../gifs/contact/hector.gif
python3 login.py kore_outdoor ../mocks/connect/kore_outdoor-logo.png ../mocks/connect/kore_outdoor.png ../gifs/contact/kore_outdoor.gif
python3 login.py copper_pearl ../mocks/connect/copper_pearl-logo.png ../mocks/connect/copper_pearl.png ../gifs/contact/copper_pearl.gif
python3 login.py sitka ../mocks/connect/sitka-logo.png ../mocks/connect/sitka.png ../gifs/contact/sitka.gif
python3 login.py clarcorp ../mocks/connect/clarcorp-logo.png ../mocks/connect/clarcorp.png ../gifs/contact/clarcorp.gif
python3 login.py bertram ../mocks/connect/bertram-logo.png ../mocks/connect/bertram.png ../gifs/contact/bertram.gif
python3 login.py specialty_produce ../mocks/connect/specialty_produce-logo.png ../mocks/connect/specialty_produce.png ../gifs/contact/specialty_produce.gif
python3 login.py commonwealth_packaging ../mocks/connect/commonwealth_packaging-logo.png ../mocks/connect/commonwealth_packaging.png ../gifs/contact/commonwealth_packaging.gif
python3 login.py college_city_beverage ../mocks/connect/college_city_beverage-logo.png ../mocks/connect/college_city_beverage.png ../gifs/contact/college_city_beverage.gif
python3 login.py essential_medical_supply ../mocks/connect/essential_medical_supply-logo.png ../mocks/connect/essential_medical_supply.png ../gifs/contact/essential_medical_supply.gif
python3 login.py manamed ../mocks/connect/manamed-logo.png ../mocks/connect/manamed.png ../gifs/contact/manamed.gif
python3 login.py to_market ../mocks/connect/to_market-logo.png ../mocks/connect/to_market.png ../gifs/contact/to_market.gif
python3 login.py united_aqua_group ../mocks/connect/united_aqua_group-logo.png ../mocks/connect/united_aqua_group.png ../gifs/contact/united_aqua_group.gif
python3 login.py milkhouse_candle ../mocks/connect/milkhouse_candle-logo.png ../mocks/connect/milkhouse_candle.png ../gifs/contact/milkhouse_candle.gif
