python3 checkout.py ../mocks/checkouts/not_done/purely_elizabeth_checkout.png ../gifs/temp/purely_elizabeth_checkout.png.gif
python3 checkout.py ../mocks/checkouts/not_done/hill_n_markes_checkout.png ../gifs/temp/hill_n_markes_checkout.png.gif
python3 checkout.py ../mocks/checkouts/not_done/hubert_checkout.png ../gifs/temp/hubert_checkout.png.gif
python3 checkout.py ../mocks/checkouts/not_done/electric_fence_company_checkout.png ../gifs/temp/electric_fence_company_checkout.png.gif
python3 checkout.py ../mocks/checkouts/not_done/groomers_choice_checkout.png ../gifs/temp/groomers_choice_checkout.png.gif
python3 checkout.py ../mocks/checkouts/not_done/fatty_checkout.png ../gifs/temp/fatty_checkout.png.gif
python3 checkout.py ../mocks/checkouts/not_done/laird_superfood-checkout.png ../gifs/temp/laird_superfood.gif
python3 checkout.py ../mocks/checkouts/not_done/high_brew_checkout.png ../gifs/temp/high_brew_checkout.png.gif
python3 checkout.py ../mocks/checkouts/not_done/lawley_checkout.png ../gifs/temp/lawley_checkout.png.gif
python3 checkout.py ../mocks/checkouts/not_done/harmless_harvest_checkout.png ../gifs/temp/harmless_harvest_checkout.png.gif
python3 checkout.py ../mocks/checkouts/not_done/northwest_computer_acessories.png ../gifs/temp/northwest_computer_acessories.png.gif
python3 checkout.py ../mocks/checkouts/not_done/devil_mountain_checkout.png ../gifs/temp/devil_mountain_checkout.png.gif
