python3 checkout.py ../mocks/checkouts/not_done/katom-checkout.png ../gifs/temp/katom.gif
python3 checkout.py ../mocks/checkouts/not_done/mars-checkout.png ../gifs/temp/mars.gif
python3 checkout.py ../mocks/checkouts/not_done/.DS_Store ../gifs/temp/.DS_Store.gif
python3 checkout.py ../mocks/checkouts/not_done/deacon-items.png ../gifs/temp/deacon.gif
python3 checkout.py ../mocks/checkouts/not_done/eastern-checkout.png ../gifs/temp/eastern.gif
python3 checkout.py ../mocks/checkouts/not_done/kalalou-checkout.png ../gifs/temp/kalalou.gif
python3 checkout.py ../mocks/checkouts/not_done/fetco-checkout.png ../gifs/temp/fetco.gif
python3 checkout.py ../mocks/checkouts/not_done/springfieldelectric-checkout.png ../gifs/temp/springfieldelectric.gif
python3 checkout.py ../mocks/checkouts/not_done/americanpipe-items.png ../gifs/temp/americanpipe.gif
python3 checkout.py ../mocks/checkouts/not_done/sweetnothings-checkout.png ../gifs/temp/sweetnothings.gif
python3 checkout.py ../mocks/checkouts/not_done/burtonburton-checkout.png ../gifs/temp/burtonburton.gif
python3 checkout.py ../mocks/checkouts/not_done/once_upon_a_farm-checkout.png ../gifs/temp/once_upon_a_farm.gif
python3 checkout.py ../mocks/checkouts/not_done/americancanning-checkout.png ../gifs/temp/americancanning.gif
python3 checkout.py ../mocks/checkouts/not_done/savory-checkout.png ../gifs/temp/savory.gif
python3 checkout.py ../mocks/checkouts/not_done/hardwarespecialty-checkout.png ../gifs/temp/hardwarespecialty.gif
python3 checkout.py ../mocks/checkouts/not_done/bern-checkout.png ../gifs/temp/bern.gif
python3 checkout.py ../mocks/checkouts/not_done/prologicgroup-checkout.png ../gifs/temp/prologicgroup.gif
python3 checkout.py ../mocks/checkouts/not_done/hartman-checkout.png ../gifs/temp/hartman.gif
python3 checkout.py ../mocks/checkouts/not_done/uhs-checkout.png ../gifs/temp/uhs.gif
python3 checkout.py ../mocks/checkouts/not_done/ingredienthouse-checkout.png ../gifs/temp/ingredienthouse.gif
python3 checkout.py ../mocks/checkouts/not_done/abatix-checkout.png ../gifs/temp/abatix.gif
python3 checkout.py ../mocks/checkouts/not_done/samtell-checkout.png ../gifs/temp/samtell.gif
python3 checkout.py ../mocks/checkouts/not_done/vamac-items.png ../gifs/temp/vamac.gif
